### ISSUE TITLE
need help trying to run your project

### ISSUE THREAD

**Issue by Dev-Fouad** [TheRealFlyingCoder/remix-sort-filter-search-table#1]
hi, the realflyingcoder

i just cloned your work to give me idea how i could implement mine. can you give me few minutes of your time to help me solve those errors. nice work man

**Comment by Dev-Fouad** [comment]
ReferenceError: prismaRead is not defined
    at getCount (C:\Users\hp\table\remix-sort-filter-search-table\build\index.js:1002:20)
    at getPaginatedOrders (C:\Users\hp\table\remix-sort-filter-search-table\build\index.js:1011:36)
    at loader (C:\Users\hp\table\remix-sort-filter-search-table\build\index.js:1020:22)
    at Object.callRouteLoader (C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\server-runtime\data.js:73:20)
    at C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\server-runtime\server.js:270:113
    at Array.map (<anonymous>)
    at renderDocumentRequest (C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\server-runtime\server.js:270:67)
    at requestHandler (C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\server-runtime\server.js:55:26)
    at C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\express\server.js:45:28
    at C:\Users\hp\table\remix-sort-filter-search-table\node_modules\@remix-run\serve\index.js:44:7
